#ifndef CONFIG_H
#define CONFIG_H

#define PIN_RX 16
#define PIN_TX 7

#define PIN_SENSOR_SDA_F 13
#define PIN_SENSOR_SCL_F 12
#define PIN_SENSOR_DIR_F 11

#define ALL_ENGINE_BRAKE_PIN 45
#define ALL_ENGINE_SPEED_CONTROL_PIN 35
#define ALL_ENGINE_DIRECTION_CONTROL_PIN 37

#define ROTATION_SPEED_LEFT_PIN_F 4
#define ROTATION_SPEED_RIGHT_PIN_F 6

#define ROTATION_SPEED_LEFT_PIN_B 15
#define ROTATION_SPEED_RIGHT_PIN_B 8

// encoders
#define PIN_SENSOR_SDA_B 10
#define PIN_SENSOR_SCL_B 9
#define PIN_SENSOR_DIR_B 46

#define PIN_LED_STRIP_F 20
#define PIN_LED_STRIP_B 19
#define NUM_PIXELS 20

// ELRS channels
#define ROTATION_CHANNEL 1
#define SPEED_CHANNEL 3
#define ROTATION_TYPE_CHANNEL 5
#define DIRECTION_CHANNEL 6
#define BRAKE_CHANNEL 7
#define RESET_CHANNEL 8

#endif